<%@ Page Title="Portfolio Admin" Language="C#"
    MasterPageFile="~/Site.Master"
    AutoEventWireup="true"
    CodeBehind="Default.aspx.cs"
    Inherits="Arvisportfolio._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    
    <!-- Header Section -->
    <div class="row mb-4">
        <div class="col-md-8">
            <h2><i class="fas fa-user-edit"></i> Portfolio Administration</h2>
            <p class="text-muted">Manage your personal information and portfolio content</p>
        </div>
        <div class="col-md-4 text-end">
            <a href="index.html" target="_blank" class="btn btn-primary">
                <i class="fas fa-eye"></i> View Live Portfolio
            </a>
        </div>
    </div>

    <!-- Alert/Message Section -->
    <asp:Label ID="lblMsg" runat="server" EnableViewState="false" CssClass="alert alert-info d-block" />

    <!-- Form Section -->
    <div class="card mb-4">
        <div class="card-header">
            <h4 class="card-title mb-0"><i class="fas fa-plus-circle"></i> Add/Update Personal Information</h4>
        </div>
        <div class="card-body">
            <div class="row g-3">
                <div class="col-md-6">
                    <label for="<%= txtName.ClientID %>" class="form-label">Full Name</label>
                    <asp:TextBox ID="txtName" runat="server" CssClass="form-control" Placeholder="Enter your full name"></asp:TextBox>
                </div>
                <div class="col-md-6">
                    <label for="<%= txtTitle.ClientID %>" class="form-label">Professional Title</label>
                    <asp:TextBox ID="txtTitle" runat="server" CssClass="form-control" Placeholder="e.g., Full Stack Developer"></asp:TextBox>
                </div>
                <div class="col-md-6">
                    <label for="<%= txtEmail.ClientID %>" class="form-label">Email Address</label>
                    <asp:TextBox ID="txtEmail" runat="server" CssClass="form-control" Placeholder="your.email@domain.com" TextMode="Email"></asp:TextBox>
                </div>
                <div class="col-md-6">
                    <label for="<%= txtPhone.ClientID %>" class="form-label">Phone Number</label>
                    <asp:TextBox ID="txtPhone" runat="server" CssClass="form-control" Placeholder="+1 (555) 123-4567" TextMode="Phone"></asp:TextBox>
                </div>
                <div class="col-12">
                    <label for="<%= txtDesc.ClientID %>" class="form-label">Professional Description</label>
                    <asp:TextBox ID="txtDesc" runat="server" TextMode="MultiLine" Rows="4" CssClass="form-control"
                                 Placeholder="Write a brief professional description or bio that will appear on your portfolio..."></asp:TextBox>
                </div>
                <div class="col-12">
                    <asp:Button ID="btnAdd" runat="server" Text="Save Information" OnClick="btnAdd_Click" 
                                CssClass="btn btn-success btn-lg" />
                    <button type="button" class="btn btn-secondary btn-lg ms-2" onclick="clearForm()">
                        <i class="fas fa-times"></i> Clear Form
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Data Grid Section -->
    <div class="card">
        <div class="card-header">
            <h4 class="card-title mb-0"><i class="fas fa-table"></i> Existing Information</h4>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <asp:GridView ID="gvIntro" runat="server"
                    AutoGenerateColumns="False"
                    DataKeyNames="Id"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    OnRowEditing="gvIntro_RowEditing"
                    OnRowCancelingEdit="gvIntro_RowCancelingEdit"
                    OnRowUpdating="gvIntro_RowUpdating"
                    OnRowDeleting="gvIntro_RowDeleting"
                    CssClass="table table-striped table-hover"
                    HeaderStyle-CssClass="table-dark"
                    EditRowStyle-CssClass="table-warning"
                    EmptyDataText="No information found. Add your first entry above.">
                    <Columns>
                        <asp:BoundField DataField="Id" HeaderText="ID" ReadOnly="True" 
                                        HeaderStyle-Width="60px" ItemStyle-CssClass="text-center" />
                        <asp:BoundField DataField="Name" HeaderText="Full Name" 
                                        HeaderStyle-Width="150px" />
                        <asp:BoundField DataField="Title" HeaderText="Title" 
                                        HeaderStyle-Width="180px" />
                        <asp:BoundField DataField="Email" HeaderText="Email" 
                                        HeaderStyle-Width="200px" />
                        <asp:BoundField DataField="Phone" HeaderText="Phone" 
                                        HeaderStyle-Width="140px" />
                        <asp:BoundField DataField="Description" HeaderText="Description" 
                                        HeaderStyle-Width="300px" ItemStyle-CssClass="text-truncate" />
                    </Columns>
                    <EditRowStyle CssClass="table-warning" />
                    <EmptyDataRowStyle CssClass="text-center text-muted" />
                </asp:GridView>
            </div>
        </div>
    </div>

    <!-- Additional Actions -->
    <div class="row mt-4">
        <div class="col-12 text-center">
            <div class="btn-group" role="group">
                <a href="index.html" target="_blank" class="btn btn-outline-primary">
                    <i class="fas fa-external-link-alt"></i> View Portfolio
                </a>
                <button type="button" class="btn btn-outline-secondary" onclick="location.reload()">
                    <i class="fas fa-sync-alt"></i> Refresh Data
                </button>
                <button type="button" class="btn btn-outline-info" onclick="exportData()">
                    <i class="fas fa-download"></i> Export Data
                </button>
            </div>
        </div>
    </div>

    <!-- Custom JavaScript -->
    <script>
        function clearForm() {
            document.getElementById('<%= txtName.ClientID %>').value = '';
            document.getElementById('<%= txtTitle.ClientID %>').value = '';
            document.getElementById('<%= txtEmail.ClientID %>').value = '';
            document.getElementById('<%= txtPhone.ClientID %>').value = '';
            document.getElementById('<%= txtDesc.ClientID %>').value = '';
        }

        function exportData() {
            // Simple alert for now - you can implement actual export functionality
            alert('Export functionality can be implemented here');
        }

        // Auto-hide alerts after 5 seconds
        document.addEventListener('DOMContentLoaded', function() {
            const alerts = document.querySelectorAll('.alert');
            alerts.forEach(function(alert) {
                if (alert.textContent.trim()) {
                    setTimeout(function() {
                        alert.style.opacity = '0';
                        setTimeout(function() {
                            alert.style.display = 'none';
                        }, 500);
                    }, 5000);
                }
            });
        });
    </script>

</asp:Content>
